# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170803_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 14, 24, 11, 432651, tzinfo=utc)),
        ),
    ]
